name: Test - Dependencies
on:
  workflow_call:
  workflow_dispatch:  # to trigger manually

permissions:
  contents: read

jobs:

  coola:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      max-parallel: 8
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ '3.13', '3.12', '3.11', '3.10' ]
        package-version: [ 0.9.0 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}
          activate-environment: true

      - name: Install invoke
        run: |
          make install-invoke

      - name: Install packages
        run: |
          inv install --all-deps

      - name: Install valid package version
        uses: durandtibo/uv-install-package-action@v0.1.0
        with:
          package-name: 'coola'
          package-version: ${{ matrix.package-version }}
          python-version: ${{ matrix.python-version }}

      - name: Show python config
        run: |
          inv show-python-config

      - name: Show installed packages
        run: |
          inv show-installed-packages

      - name: Run unit tests
        run: |
          inv unit-test


  numpy:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      max-parallel: 8
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ '3.13', '3.12', '3.11', '3.10' ]
        package-version: [
          2.3.2,
          2.2.6,
          2.1.3,
          2.0.2,
        ]

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}
          activate-environment: true

      - name: Install invoke
        run: |
          make install-invoke

      - name: Install packages
        run: |
          inv install --all-deps

      - name: Install valid package version
        uses: durandtibo/uv-install-package-action@v0.1.0
        with:
          package-name: 'numpy'
          package-version: ${{ matrix.package-version }}
          python-version: ${{ matrix.python-version }}

      - name: Show python config
        run: |
          inv show-python-config

      - name: Show installed packages
        run: |
          inv show-installed-packages

      - name: Run unit tests
        run: |
          inv unit-test


  polars:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      max-parallel: 8
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ '3.13', '3.12', '3.11', '3.10' ]
        package-version: [ 1.33.0, 1.0.0 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}
          activate-environment: true

      - name: Install invoke
        run: |
          make install-invoke

      - name: Install packages
        run: |
          inv install --all-deps

      - name: Install valid package version
        uses: durandtibo/uv-install-package-action@v0.1.0
        with:
          package-name: 'polars'
          package-version: ${{ matrix.package-version }}
          python-version: ${{ matrix.python-version }}

      - name: Show python config
        run: |
          inv show-python-config

      - name: Show installed packages
        run: |
          inv show-installed-packages

      - name: Run unit tests
        run: |
          inv unit-test
